FROM python:3.8
WORKDIR /app
ENV WORKER_COUNT=5
ENV LOG_LEVEL=info
COPY . /app

RUN apt-get update && apt-get install -y build-essential python3-dev gcc musl-dev libpq-dev libffi-dev git \
      && pip install flower \
      && pip install -r requirements/deps.txt --use-feature=2020-resolver \
      && chmod +x /app/celery.sh 

CMD [ "/app/celery.sh" ]
