version: '2'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - '8000:8000'
    environment:
      HOST: "0.0.0.0"
      PORT: 8000
      DEV: 1
      ALLOWED_HOSTS: "*"
