FROM python:3.8
WORKDIR /app
ENV WORKER_COUNT=5
ENV LOG_LEVEL=info
COPY . /app

RUN apt-get update && apt-get install -y build-essential python3-dev gcc musl-dev libpq-dev libffi-dev git \
      && pip install -r requirements/deps.txt --use-feature=2020-resolver \
      && pip install gevent \
      && chmod +x /app/entrypoint.sh
RUN python manage.py collectstatic --noinput
ENTRYPOINT [ "/app/entrypoint.sh" ]
