# Generated by Django 3.1.5 on 2021-01-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResumeDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "resume_json",
                    models.JSONField(
                        default={
                            "education": [],
                            "employment": [],
                            "personal": {},
                            "skills": [],
                            "social": {},
                            "summary": {},
                        }
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
