name: New commit actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Discord notification
       env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
       uses: Ilshidur/action-discord@master
       with:
         args: 'New Commit {{ EVENT_PAYLOAD.repository.full_name }}'